# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: group-test
description: Run grouped tests in a Docker container.
inputs:
  config-file:
    required: true
    description: Test group configuraiton file
  group:
    required: true
    description: Test group name
  type:
    required: true
    description: Type of test group - pr_gate or nightly
    default: pr_gate

runs:
  using: docker
  # The path to Dockerfile should be relative to this action.yml.
  # This path has to be hardcoded instead of being parameterized.
  image: ../../../tools/docker/Dockerfile
  # The path to entrypoint.sh can be relative to the repo root,
  # because the repo root is mounted into the working dir in the container.
  # And entrypoint.sh must be executable.
  entrypoint: '.github/actions/group-test/entrypoint.sh'
  args:
    - ${{ inputs.group }}
    - ${{ inputs.type }}
    - ${{ inputs.config-file }}
