# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

name: group-test
description: Run grouped tests in a Docker container.
inputs:
  config-file:
    required: true
    description: Test group configuraiton file
  group:
    required: true
    description: Test group name
  type:
    required: true
    description: Type of test group - pr_gate or nightly
    default: pr_gate

runs:
  using: docker
  # The path to Dockerfile should be relative to this action.yml
  image: ../../../tools/docker/Dockerfile
  # entrypoint.sh must be executable
  entrypoint: '/root/Recommenders/entrypoint.sh'
  args:
    - ${{ inputs.group }}
    - ${{ inputs.type }}
    - ${{ inputs.config-file }}
