# ---------------------------------------------------------
# Copyright (c) Recommenders contributors.
# Licensed under the MIT License.
# ---------------------------------------------------------

# Tests collected in tests/test_groups.yml, are grouped based on their
# * type
#   + pr_gate
#   + nightly
#   + experimental
# * compute
#   + cpu
#   + gpu
#   + spark
#
# In order to speed up testing, the testing workflows will run the
# tests in parallel according to the groups obtained from this action.

name: Get test groups
description: This action gets test group names from the configuration
  file for the specified compute and test type.
  yq is required in the job runner to run this action.
inputs:
  compute:
    required: false
    description: Test compute - cpu, gpu or spark.
      This input is only used for nightly, not pr_gate.
    default: cpu
  config-file:
    required: true
    description: Path to test group configuration file relative to 
      the repo root
  type:
    required: true
    description: Type of test - pr_gate or nightly
outputs:
  groups:
    description: A list of test groups
    value: ${{ steps.get-test-groups.outputs.groups }}

runs:
  using: "composite"
  steps:
    - name: Get test group names
      id: get-test-groups
      shell: bash
      run: |
        if [[ ${{ inputs.type }} == "nightly" ]]; then
          TEST_GROUPS_STR=$(yq -o json -I 0
            '[.${{ inputs.type }} | keys | .[] |
             select(contains("${{ inputs.compute }}"))]'
            ${{ inputs.config-file }})
        else
          TEST_GROUPS_STR=$(yq -o json -I 0
            '.${{ inputs.type }} | keys' ${{ inputs.config-file }})
        fi
        echo "Test Groups: ${TEST_GROUPS_STR}"
        echo "groups=${TEST_GROUPS_STR}" >> $GITHUB_OUTPUT
